// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9SfLOrxnx-jM9ql5N-ZwbvRs9T3iqeaE',
    appId: '1:772284670220:web:ed1715d403b5b64c99e929',
    messagingSenderId: '772284670220',
    projectId: 'noor-e0c74',
    authDomain: 'noor-e0c74.firebaseapp.com',
    storageBucket: 'noor-e0c74.firebasestorage.app',
    measurementId: 'G-6L7QL0DTZ2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqMcZSpwXAMC-mCqUv8VuRXblrYq-F5QE',
    appId: '1:772284670220:android:c26eeed0d631f62399e929',
    messagingSenderId: '772284670220',
    projectId: 'noor-e0c74',
    storageBucket: 'noor-e0c74.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMhd9T9VPUSS9-iaEwmlPlzJUnVSxBX9w',
    appId: '1:772284670220:ios:22cf13a193ecf1d799e929',
    messagingSenderId: '772284670220',
    projectId: 'noor-e0c74',
    storageBucket: 'noor-e0c74.firebasestorage.app',
    iosBundleId: 'com.example.basicLoginScreen',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMhd9T9VPUSS9-iaEwmlPlzJUnVSxBX9w',
    appId: '1:772284670220:ios:22cf13a193ecf1d799e929',
    messagingSenderId: '772284670220',
    projectId: 'noor-e0c74',
    storageBucket: 'noor-e0c74.firebasestorage.app',
    iosBundleId: 'com.example.basicLoginScreen',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA9SfLOrxnx-jM9ql5N-ZwbvRs9T3iqeaE',
    appId: '1:772284670220:web:9546752379cab67299e929',
    messagingSenderId: '772284670220',
    projectId: 'noor-e0c74',
    authDomain: 'noor-e0c74.firebaseapp.com',
    storageBucket: 'noor-e0c74.firebasestorage.app',
    measurementId: 'G-2VS5SZDW0E',
  );
}
